# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ptlearn',
                'doc_host': 'https://Iftikaralam2021.github.io',
                'git_url': 'https://github.com/Iftikaralam2021/ptlearn',
                'lib_path': 'ptlearn'},
  'syms': {'ptlearn.core': {'ptlearn.core.foo': ('core.html#foo', 'ptlearn/core.py')}}}
